# Generated by Django 5.2.8 on 2025-11-17 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Почта')),
                ('password', models.CharField(verbose_name='Пароль')),
                ('id_role', models.ForeignKey(db_column='id_role', default=2, on_delete=django.db.models.deletion.PROTECT, to='core.roles', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'db_table': 'users',
            },
        ),
    ]
