# Generated by Django 5.2.8 on 2025-12-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата регистрации'),
        ),
    ]
