# Generated by Django 5.2.8 on 2025-12-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
    ]
