# Generated by Django 5.2.8 on 2025-11-17 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Degrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'db_table': 'academic_degrees',
            },
        ),
        migrations.CreateModel(
            name='Academic_Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'db_table': 'academic_titles',
            },
        ),
        migrations.CreateModel(
            name='Audiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_number', models.CharField(max_length=10, unique=True, verbose_name='Номер аудитории')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
            ],
            options={
                'db_table': 'audiences',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Educational_Institutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'db_table': 'educational_institutions',
            },
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'db_table': 'faculties',
            },
        ),
        migrations.CreateModel(
            name='Job_Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'db_table': 'job_titles',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Place_Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'db_table': 'place_works',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название')),
            ],
            options={
                'db_table': 'specialties',
            },
        ),
        migrations.CreateModel(
            name='Study_Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True, verbose_name='Название')),
            ],
            options={
                'db_table': 'study_groups',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=25, null=True, verbose_name='Отчество')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('occupied', models.IntegerField(default=0, verbose_name='Занято')),
            ],
            options={
                'db_table': 'tracks',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('lesson_link', models.CharField(max_length=500, verbose_name='Ссылка')),
            ],
            options={
                'db_table': 'classes',
                'unique_together': {('title', 'lesson_link')},
            },
        ),
        migrations.CreateModel(
            name='Classes_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('id_audience', models.ForeignKey(db_column='id_audience', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.audiences', verbose_name='Аудитория')),
                ('id_lesson', models.ForeignKey(db_column='id_lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classes', verbose_name='Занятие')),
                ('id_track', models.ForeignKey(db_column='id_track', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tracks', verbose_name='Трек')),
            ],
            options={
                'db_table': 'classes_schedule',
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=25, null=True, verbose_name='Отчество')),
                ('class_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=2, verbose_name='Класс')),
                ('phone_number', models.CharField(max_length=22, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Почта')),
                ('link_copy_consent', models.CharField(max_length=500, unique=True, verbose_name='Ссылка')),
                ('diploma', models.CharField(max_length=500, null=True, unique=True, verbose_name='Диплом')),
                ('id_city', models.ForeignKey(db_column='id_city', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cities', verbose_name='Город')),
                ('id_educational_institution', models.ForeignKey(db_column='id_educational_institution', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.educational_institutions', verbose_name='Учебное заведение')),
            ],
            options={
                'db_table': 'participants',
            },
        ),
        migrations.CreateModel(
            name='Participants_Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_participant', models.ForeignKey(db_column='id_participant', on_delete=django.db.models.deletion.CASCADE, to='core.participants', unique=True, verbose_name='Участник')),
                ('id_track', models.ForeignKey(db_column='id_track', on_delete=django.db.models.deletion.CASCADE, to='core.tracks', verbose_name='Трек')),
            ],
            options={
                'db_table': 'participants_tracks',
            },
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.CharField(choices=[('+', 'Присутствовал'), ('-', 'Отсутствовал')], max_length=1, verbose_name='Посещение')),
                ('id_class', models.ForeignKey(db_column='id_class', on_delete=django.db.models.deletion.CASCADE, to='core.classes', verbose_name='Занятие')),
                ('id_participant', models.ForeignKey(db_column='id_participant', on_delete=django.db.models.deletion.CASCADE, to='core.participants', verbose_name='Участник')),
            ],
            options={
                'db_table': 'visits',
                'unique_together': {('id_class', 'id_participant')},
            },
        ),
        migrations.AddField(
            model_name='participants',
            name='visited_classes',
            field=models.ManyToManyField(through='core.Visits', through_fields=('id_participant', 'id_class'), to='core.classes', verbose_name='Посещенные занятия'),
        ),
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=25, null=True, verbose_name='Отчество')),
                ('course', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=1, verbose_name='Курс')),
                ('id_faculty', models.ForeignKey(db_column='id_faculty', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faculties', verbose_name='Факультет')),
                ('id_group', models.ForeignKey(db_column='id_group', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.study_groups', verbose_name='Группа')),
                ('id_speciality', models.ForeignKey(db_column='id_speciality', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.specialties', verbose_name='Специальность')),
            ],
            options={
                'db_table': 'volunteers',
            },
        ),
        migrations.CreateModel(
            name='Accesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_info', models.BooleanField(verbose_name='Просмотр')),
                ('edit_info', models.BooleanField(verbose_name='Изменение')),
                ('write_info', models.BooleanField(verbose_name='Добавление')),
                ('delete_info', models.BooleanField(verbose_name='Удаление')),
                ('id_menu', models.ForeignKey(db_column='id_menu', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.menu', verbose_name='Пункт меню')),
                ('id_role', models.ForeignKey(db_column='id_role', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.roles', verbose_name='Роль')),
            ],
            options={
                'db_table': 'accesses',
                'unique_together': {('id_role', 'id_menu')},
            },
        ),
        migrations.CreateModel(
            name='Teacher_Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_class_schedule', models.ForeignKey(db_column='id_class_schedule', on_delete=django.db.models.deletion.CASCADE, to='core.classes_schedule', verbose_name='Расписание занятия')),
                ('id_teacher', models.ForeignKey(db_column='id_teacher', on_delete=django.db.models.deletion.CASCADE, to='core.teachers', verbose_name='Преподаватель')),
            ],
            options={
                'db_table': 'teacher_schedules',
                'unique_together': {('id_teacher', 'id_class_schedule')},
            },
        ),
        migrations.CreateModel(
            name='Teachers_Academic_Degrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_academic_degree', models.ForeignKey(db_column='id_academic_degree', on_delete=django.db.models.deletion.CASCADE, to='core.academic_degrees', verbose_name='Учёная степень')),
                ('id_teacher', models.ForeignKey(db_column='id_teacher', on_delete=django.db.models.deletion.CASCADE, to='core.teachers', verbose_name='Преподаватель')),
            ],
            options={
                'db_table': 'teachers_academic_degrees',
                'unique_together': {('id_teacher', 'id_academic_degree')},
            },
        ),
        migrations.CreateModel(
            name='Teachers_Academic_Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_academic_title', models.ForeignKey(db_column='id_academic_title', on_delete=django.db.models.deletion.CASCADE, to='core.academic_titles', verbose_name='Учёное звание')),
                ('id_teacher', models.ForeignKey(db_column='id_teacher', on_delete=django.db.models.deletion.CASCADE, to='core.teachers', verbose_name='Преподаватель')),
            ],
            options={
                'db_table': 'teachers_academic_titles',
                'unique_together': {('id_teacher', 'id_academic_title')},
            },
        ),
        migrations.CreateModel(
            name='Teachers_Job_Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_job_title', models.ForeignKey(db_column='id_job_title', on_delete=django.db.models.deletion.CASCADE, to='core.job_titles', verbose_name='Должность')),
                ('id_teacher', models.ForeignKey(db_column='id_teacher', on_delete=django.db.models.deletion.CASCADE, to='core.teachers', verbose_name='Преподаватель')),
            ],
            options={
                'db_table': 'teachers_job_titles',
                'unique_together': {('id_teacher', 'id_job_title')},
            },
        ),
        migrations.CreateModel(
            name='Teachers_Place_Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_place_work', models.ForeignKey(db_column='id_place_work', on_delete=django.db.models.deletion.CASCADE, to='core.place_works', verbose_name='Место работы')),
                ('id_teacher', models.ForeignKey(db_column='id_teacher', on_delete=django.db.models.deletion.CASCADE, to='core.teachers', verbose_name='Преподаватель')),
            ],
            options={
                'db_table': 'teachers_place_works',
                'unique_together': {('id_teacher', 'id_place_work')},
            },
        ),
        migrations.CreateModel(
            name='Teacher_Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_teacher', models.ForeignKey(db_column='id_teacher', on_delete=django.db.models.deletion.CASCADE, to='core.teachers', verbose_name='Преподаватель')),
                ('id_track', models.ForeignKey(db_column='id_track', on_delete=django.db.models.deletion.CASCADE, to='core.tracks', verbose_name='Трек')),
            ],
            options={
                'db_table': 'teacher_tracks',
                'unique_together': {('id_teacher', 'id_track')},
            },
        ),
        migrations.CreateModel(
            name='Volunteer_Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_track', models.ForeignKey(db_column='id_track', on_delete=django.db.models.deletion.CASCADE, to='core.tracks', verbose_name='Трек')),
                ('id_volunteer', models.ForeignKey(db_column='id_volunteer', on_delete=django.db.models.deletion.CASCADE, to='core.volunteers', verbose_name='Волонтёр')),
            ],
            options={
                'db_table': 'volunteer_tracks',
                'unique_together': {('id_volunteer', 'id_track')},
            },
        ),
    ]
