# Generated by Django 5.2.8 on 2025-11-19 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academic_degrees',
            options={'verbose_name': 'Учёная степень', 'verbose_name_plural': 'Учёные степени'},
        ),
        migrations.AlterModelOptions(
            name='academic_titles',
            options={'verbose_name': 'Учёное звание', 'verbose_name_plural': 'Учёные звания'},
        ),
        migrations.AlterModelOptions(
            name='accesses',
            options={'verbose_name': 'Права доступа', 'verbose_name_plural': 'Права доступа'},
        ),
        migrations.AlterModelOptions(
            name='audiences',
            options={'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'Занятие', 'verbose_name_plural': 'Зантия'},
        ),
        migrations.AlterModelOptions(
            name='classes_schedule',
            options={'verbose_name': 'Расписание занятий', 'verbose_name_plural': 'Расписания занятий'},
        ),
        migrations.AlterModelOptions(
            name='educational_institutions',
            options={'verbose_name': 'Учебное заведение', 'verbose_name_plural': 'Учебные заведения'},
        ),
        migrations.AlterModelOptions(
            name='faculties',
            options={'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='job_titles',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='participants',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='participants_tracks',
            options={'verbose_name': 'Трек участника', 'verbose_name_plural': 'Треки участников'},
        ),
        migrations.AlterModelOptions(
            name='place_works',
            options={'verbose_name': 'Место работы', 'verbose_name_plural': 'Места работы'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='specialties',
            options={'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.AlterModelOptions(
            name='study_groups',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='teacher_schedules',
            options={'verbose_name': 'Расписание преподавателя', 'verbose_name_plural': 'Расписание преподавателей'},
        ),
        migrations.AlterModelOptions(
            name='teacher_tracks',
            options={'verbose_name': 'Трек преподавателя', 'verbose_name_plural': 'Треки преподавателей'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='teachers_academic_degrees',
            options={'verbose_name': 'Учёная степень преподавателя', 'verbose_name_plural': 'Учёные степени преподавателей'},
        ),
        migrations.AlterModelOptions(
            name='teachers_academic_titles',
            options={'verbose_name': 'Учёное звание преподавателя', 'verbose_name_plural': 'Учёные звания преподавателей'},
        ),
        migrations.AlterModelOptions(
            name='teachers_job_titles',
            options={'verbose_name': 'Должность преподавателя', 'verbose_name_plural': 'Должности преподавателей'},
        ),
        migrations.AlterModelOptions(
            name='teachers_place_works',
            options={'verbose_name': 'Место работы преподавателя', 'verbose_name_plural': 'Места работы преподавателей'},
        ),
        migrations.AlterModelOptions(
            name='tracks',
            options={'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AlterModelOptions(
            name='visits',
            options={'verbose_name': 'Посещение', 'verbose_name_plural': 'Посещения'},
        ),
        migrations.AlterModelOptions(
            name='volunteer_tracks',
            options={'verbose_name': 'Трек волонтёра', 'verbose_name_plural': 'Треки волонтёров'},
        ),
        migrations.AlterModelOptions(
            name='volunteers',
            options={'verbose_name': 'Волонтёр', 'verbose_name_plural': 'Волонтёры'},
        ),
        migrations.AlterField(
            model_name='tracks',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='occupied',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Занято'),
        ),
    ]
