# Generated by Django 5.2.8 on 2025-11-24 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_academic_degrees_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academic_degrees',
            options={'ordering': ['title'], 'verbose_name': 'Учёная степень', 'verbose_name_plural': 'Учёные степени'},
        ),
        migrations.AlterModelOptions(
            name='academic_titles',
            options={'ordering': ['title'], 'verbose_name': 'Учёное звание', 'verbose_name_plural': 'Учёные звания'},
        ),
        migrations.AlterModelOptions(
            name='audiences',
            options={'ordering': ['audience_number'], 'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'ordering': ['title'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='classes',
            options={'ordering': ['title'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterModelOptions(
            name='classes_schedule',
            options={'ordering': ['lesson_date', 'start_time', 'end_time'], 'verbose_name': 'Расписание занятий', 'verbose_name_plural': 'Расписания занятий'},
        ),
        migrations.AlterModelOptions(
            name='educational_institutions',
            options={'ordering': ['title'], 'verbose_name': 'Учебное заведение', 'verbose_name_plural': 'Учебные заведения'},
        ),
        migrations.AlterModelOptions(
            name='faculties',
            options={'ordering': ['title'], 'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='job_titles',
            options={'ordering': ['title'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['title'], 'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='participants',
            options={'ordering': ['last_name', 'first_name', 'patronymic'], 'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='participants_tracks',
            options={'ordering': ['id_participant'], 'verbose_name': 'Трек участника', 'verbose_name_plural': 'Треки участников'},
        ),
        migrations.AlterModelOptions(
            name='place_works',
            options={'ordering': ['title'], 'verbose_name': 'Место работы', 'verbose_name_plural': 'Места работы'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'ordering': ['title'], 'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='specialties',
            options={'ordering': ['title'], 'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.AlterModelOptions(
            name='study_groups',
            options={'ordering': ['title'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='teacher_schedules',
            options={'ordering': ['id_teacher'], 'verbose_name': 'Расписание преподавателя', 'verbose_name_plural': 'Расписание преподавателей'},
        ),
        migrations.AlterModelOptions(
            name='teacher_tracks',
            options={'ordering': ['id_teacher'], 'verbose_name': 'Трек преподавателя', 'verbose_name_plural': 'Треки преподавателей'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'ordering': ['last_name', 'first_name', 'patronymic'], 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='teachers_academic_degrees',
            options={'ordering': ['id_teacher'], 'verbose_name': 'Учёная степень преподавателя', 'verbose_name_plural': 'Учёные степени преподавателей'},
        ),
        migrations.AlterModelOptions(
            name='teachers_academic_titles',
            options={'ordering': ['id_teacher'], 'verbose_name': 'Учёное звание преподавателя', 'verbose_name_plural': 'Учёные звания преподавателей'},
        ),
        migrations.AlterModelOptions(
            name='teachers_job_titles',
            options={'ordering': ['id_teacher'], 'verbose_name': 'Должность преподавателя', 'verbose_name_plural': 'Должности преподавателей'},
        ),
        migrations.AlterModelOptions(
            name='teachers_place_works',
            options={'ordering': ['id_teacher'], 'verbose_name': 'Место работы преподавателя', 'verbose_name_plural': 'Места работы преподавателей'},
        ),
        migrations.AlterModelOptions(
            name='tracks',
            options={'ordering': ['title'], 'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AlterModelOptions(
            name='visits',
            options={'ordering': ['id_participant'], 'verbose_name': 'Посещение', 'verbose_name_plural': 'Посещения'},
        ),
        migrations.AlterModelOptions(
            name='volunteer_tracks',
            options={'ordering': ['id_volunteer'], 'verbose_name': 'Трек волонтёра', 'verbose_name_plural': 'Треки волонтёров'},
        ),
        migrations.AlterModelOptions(
            name='volunteers',
            options={'ordering': ['last_name', 'first_name', 'patronymic'], 'verbose_name': 'Волонтёр', 'verbose_name_plural': 'Волонтёры'},
        ),
        migrations.AlterField(
            model_name='academic_degrees',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Учёная степень'),
        ),
        migrations.AlterField(
            model_name='academic_titles',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Учёное звание'),
        ),
        migrations.AlterField(
            model_name='audiences',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Вместимость аудитории'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='lesson_link',
            field=models.CharField(max_length=500, verbose_name='Ссылка на занятие'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название занятия'),
        ),
        migrations.AlterField(
            model_name='educational_institutions',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='job_titles',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='place_works',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='specialties',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='study_groups',
            name='title',
            field=models.CharField(max_length=25, unique=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Вместимость трека'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='occupied',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Занятость трека'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название трека'),
        ),
    ]
