# Generated by Django 5.2.8 on 2025-11-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_academic_degrees_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='visited_classes',
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Пункт меню'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='diploma',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Диплом'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Роль'),
        ),
    ]
