# Generated by Django 5.2.8 on 2025-12-12 13:40

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_participants_visited_classes_alter_menu_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action_Logging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('action', models.CharField(choices=[('add', 'Добавление'), ('update', 'Изменение'), ('delete', 'Удаление')], max_length=20, verbose_name='Действие')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Запись действия',
                'verbose_name_plural': 'Журнал дийсвий',
                'db_table': 'action_logging',
                'ordering': ['-datetime'],
            },
        ),
        migrations.AlterModelOptions(
            name='participants',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='volunteers',
            options={'verbose_name': 'Волонтёр', 'verbose_name_plural': 'Волонтёры'},
        ),
        migrations.AlterField(
            model_name='audiences',
            name='capacity',
            field=models.PositiveIntegerField(validators=[core.validators.audience_capacity_validator], verbose_name='Вместимость аудитории'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='lesson_link',
            field=models.URLField(max_length=500, verbose_name='Ссылка на занятие'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='diploma',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на диплом'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='first_name',
            field=models.CharField(max_length=25, validators=[core.validators.name_validator], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='last_name',
            field=models.CharField(max_length=25, validators=[core.validators.name_validator], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='link_copy_consent',
            field=models.URLField(max_length=500, unique=True, verbose_name='Ссылка на согласие на обработку персональных данных'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='patronymic',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[core.validators.name_validator], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='phone_number',
            field=models.CharField(max_length=22, unique=True, validators=[core.validators.phone_number_validator], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='teacher_schedules',
            name='id_class_schedule',
            field=models.ForeignKey(db_column='id_class_schedule', on_delete=django.db.models.deletion.CASCADE, to='core.classes_schedule', unique=True, verbose_name='Расписание занятия'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='first_name',
            field=models.CharField(max_length=25, validators=[core.validators.name_validator], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='last_name',
            field=models.CharField(max_length=25, validators=[core.validators.name_validator], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='patronymic',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[core.validators.name_validator], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='capacity',
            field=models.PositiveIntegerField(validators=[core.validators.track_capacity_validator], verbose_name='Вместимость трека'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='occupied',
            field=models.PositiveIntegerField(default=0, verbose_name='Занятость трека'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='title',
            field=models.CharField(max_length=200, unique=True, validators=[core.validators.title_validator], verbose_name='Название трека'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='first_name',
            field=models.CharField(max_length=25, validators=[core.validators.name_validator], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='last_name',
            field=models.CharField(max_length=25, validators=[core.validators.name_validator], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='patronymic',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[core.validators.name_validator], verbose_name='Отчество'),
        ),
    ]
