# Generated by Django 5.2.8 on 2025-12-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_action_logging_alter_participants_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action_logging',
            options={'ordering': ['-datetime'], 'verbose_name': 'Запись действия', 'verbose_name_plural': 'Журнал действий'},
        ),
    ]
