# Generated by Django 5.2.8 on 2025-12-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_action_logging_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action_logging',
            old_name='model_name',
            new_name='table_name',
        ),
    ]
